### ISSUE TITLE
Failed to reproduce similar model metrics

### ISSUE THREAD

**Issue by RawanLaz** [v-iashin/BMT#25]
I tried to reproduce similar model by training the model on the same dataset with the same parameters you provided in the repository, but whatever I do or how long I train the model, I keep not reaching similar results or metrics... can you please tell me why do you think this happens? and how many epochs you trained your model?

Thanks

**Comment by v-iashin** [comment]
Hi, I am sorry to hear that you couldn't match the same performance and I am not sure why it happens in your case based on the information you provided.

There are some reproducibility difficulties due to randomness in training as noted here: https://github.com/v-iashin/BMT#reproducibility-note.

We have Section 6.3 with more implementation details in our paper. Please, check it out to see how long you need to train the models.

Note, we also evaluate our model on the filtered ground truth files (in `./data`) instead of the original ones because we do not have access to the full dataset (see https://github.com/v-iashin/BMT/issues/17).

**Comment by RawanLaz** [comment]
Thanks for your detailed answer. I will recheck the paper and retrain according to it.

**Comment by v-iashin** [comment]
Hi, why did you close it? Did you find the problem? How did you solve it?

**Comment by RawanLaz** [comment]
Sorry for my very late response. I tried training the proposal generation model for more epochs and I reached better results. Not as good as yours but I didn't continue training until the stopping point in the code.
