### ISSUE TITLE
Uni-modal/Bi-modal Training

### ISSUE THREAD

**Issue by engindeniz** [v-iashin/BMT#27]
Hello,

Thank you for sharing the code and responding to all issues. I have two questions:

1. For the uni-modal training, did you use the "linear embedder"? 
2.  How did you decide the dimension of internal space (d_model) for bi-modal training? Should it be the same as the dimension of the video feature?

**Comment by v-iashin** [comment]
Hi! Oh, this question challenges my memory 🙂.

1. No, we didn't, afair.
2. We use the generalised Multi-headed attention which maps the qkv into its internal space which allows qkv to have an arbitrary dimension. It is useful because our multi-modal features have different dims (e.g. audio 128 and visual 1024).
https://github.com/v-iashin/BMT/blob/18b5ee109ac48e6023bad5d8c52b3a9c9c53e86f/model/multihead_attention.py#L46-L49
`d_model` is a hyper-parameter that happens to coincide with the size of i3d features.
https://github.com/v-iashin/BMT/blob/18b5ee109ac48e6023bad5d8c52b3a9c9c53e86f/main.py#L126-L132

**Comment by engindeniz** [comment]
Thank you so much for your answers.

The first question refers to this parameter:

https://github.com/v-iashin/BMT/blob/d45ad8f11d35bc7d1757ac1d735952384b4fa4c1/main.py#L141-L144

Did you use this parameter in any of your training (uni/bi modal)?

In the paper (section 4.2 Ablation Study), you mentioned that "For the uni-modal transformer, we follow the original paper where the input is first embedded into Dq dimension ...". That's why I thought that you used lineer_embedder.

**Comment by v-iashin** [comment]
Yes, I understand your concern. I think it is not clear in the paper. In that line I meant to contrast the way we deal with input depending on the setting. Specifically,

1) for multi-modal setting we keep the flowing features (audio, visual, caption)  for each Encoder/Decoder layer in the same size as they are on the input and only expand it to `d_model` in `Multi-Headed Attention`.
2) for uni-modal setting we, in contrast, map the Transformer's input to `D_q` as in the original Vanilla transformer with word tokens. However, in the Audio-only case, it only applies to captions (vocab -> Dq) because the dimension of audio features is already Dq(=128) and we decided to avoid another remapping into the same space (which the linear embedder would do).

I hope this explanation clarifies your concerns. Very good and deep question!

**Comment by engindeniz** [comment]
Thanks for the answers, but I am confused about your answer especially the second one. 

I supposed that the "Vocab --> Dq" case applies in every setting, only `D_q` changes.

https://github.com/v-iashin/BMT/blob/d45ad8f11d35bc7d1757ac1d735952384b4fa4c1/model/captioning_module.py#L37

https://github.com/v-iashin/BMT/blob/d45ad8f11d35bc7d1757ac1d735952384b4fa4c1/model/captioning_module.py#L121

As far as I understood, you did not use the `use_linear_embedder` parameter in any settings. Is this correct?

**Comment by v-iashin** [comment]
The items in my previous post are not the answers to your initial questions but a description of two different settings. 

Yes, again, we do not use that argument in neither of the settings. 

Yes, Vocab embedding applies in all settings to captions. 

That sentence in the paper is there to emphasize that, in the uni-modal case, internal space of multi-headed attention has the same size as the input features (128 in audio, 1028 in visual) and the input (audio wave and frames are mapped to it by vggish and i3d).

**Comment by engindeniz** [comment]
It is more clear now. Thank you for your helpful answers.
